POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Nick Fury",
    "number": "12-0000001"
}
# Validation error name required and unique, number required, number more than 8, name more than 3